/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package master;

/**
 *
 * @author Colin
 */
public class picker extends javax.swing.JFrame {

    /**
     * Creates new form picker
     */
    public picker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("jButton1");
        jButton1.setOpaque(false);
        getContentPane().add(jButton1);
        jButton1.setBounds(71, 116, 160, 120);

        jButton2.setText("jButton2");
        getContentPane().add(jButton2);
        jButton2.setBounds(70, 230, 160, 120);

        jButton3.setText("jButton3");
        getContentPane().add(jButton3);
        jButton3.setBounds(70, 350, 160, 110);

        jButton4.setText("jButton4");
        getContentPane().add(jButton4);
        jButton4.setBounds(70, 456, 160, 130);

        jButton5.setText("jButton5");
        getContentPane().add(jButton5);
        jButton5.setBounds(320, 130, 170, 110);

        jButton6.setText("jButton6");
        getContentPane().add(jButton6);
        jButton6.setBounds(320, 236, 170, 120);

        jButton7.setText("jButton7");
        getContentPane().add(jButton7);
        jButton7.setBounds(320, 356, 170, 120);

        jButton8.setText("jButton8");
        getContentPane().add(jButton8);
        jButton8.setBounds(320, 476, 170, 120);

        jButton9.setText("jButton9");
        getContentPane().add(jButton9);
        jButton9.setBounds(580, 116, 180, 130);

        jButton10.setText("jButton10");
        getContentPane().add(jButton10);
        jButton10.setBounds(580, 246, 180, 120);

        jButton11.setText("jButton11");
        getContentPane().add(jButton11);
        jButton11.setBounds(580, 366, 180, 110);

        jButton12.setText("jButton12");
        getContentPane().add(jButton12);
        jButton12.setBounds(580, 476, 180, 110);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guis/background/background.png"))); // NOI18N
        jLabel2.setFocusable(false);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(picker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(picker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(picker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(picker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new picker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
